version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: test-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    networks:
      - test-network

  products-api:
    image: eduardo2704garcia/products-api:v1
    container_name: c-app-products
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWORD: admin123
      DB_DATABASE: test
      PORT: 8003
    ports:
      - "8081:8003"
    depends_on:
      - db
    networks:
      - test-network

  categories-api:
    image: eduardo2704garcia/categories-api:v2
    container_name: c-app-categorias
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWORD: admin123
      DB_DATABASE: test
      PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - test-network

  frontend:
    image: eduardo2704garcia/frontend-gestion:v1
    container_name: c-frontend-gestion
    ports:
      - "4200:80"
    depends_on:
      - products-api
      - categories-api
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
